# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  test:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "yarn-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: yarn install
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "yarn-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Install jq
          command: cd e2e && apt-get install jq xsel  

      # run tests!
      - run: yarn test:coverage

      - store_test_results:
          path: testReports
          when: always

      - store_artifacts:
          path: coverage

      # run build!
      - run: yarn build

      # run linters!
      - run: yarn lint

      # # run the app!
      - run: yarn ci

      - run:
          name: Combine MochaAwesome Reports
          when: always
          command: make combine-reports     
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: mochareports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
    #   - run:
    #       name: Publish test artefacts s3 bucket
    #       when: always
    #       command: make publish-reports-s3
      - run:
          name: Slack Custom Reporting
          when: always
          command: make slack-alert 