# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  test:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:12.18.2
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v5-deps-{{ .Branch }}-
            - v5-deps-
      - run: yarn install
      - save_cache:
          key: v5-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Install jq
          command: apt-get update && apt-get install -y jq xsel  

      # run tests!
      - run: yarn test:coverage

      - store_test_results:
          path: testReports
          when: always

      - store_artifacts:
          path: coverage

      # run build!
      - run: yarn build

      # run linters!
      - run: yarn lint

      # # run the app!
      - run: make test-ci
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: mochareports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - run:
          name: Combine MochaAwesome json Reports
          when: always
          command: make combine-reports
      - run:
          name: generate MochaAwesome html Reports
          when: always
          command: make generate-report 
      - run:
          name: Slack Custom Reporting
          when: always
          command: make slack-alert 

workflows:
  build-test:
    jobs:
      - test
