# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.15.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test:coverage

      - store_test_results:
          path: testReports
          when: always

      - store_artifacts:
          path: coverage

      # run build!
      - run: yarn build

      # run linters!
      - run: yarn lint

      # # run the app!
      - run: yarn ci

      - run:
          name: Combine MochaAwesome Reports
          when: always
          command: make combine-reports     
      - store_test_results:
          path: cypress/reports
      - store_artifacts:
          path: mochareports
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
    #   - run:
    #       name: Publish test artefacts s3 bucket
    #       when: always
    #       command: make publish-reports-s3
      - run:
          name: Slack Custom Reporting
          when: always
          command: make slack-alert 